[workspace]
resolver = "2"

members = ["lib", "graph", "runtime", "runtime-ffi", "data", "lib-macros"]

[workspace.dependencies]
anyhow = "1.0"
bytes = "1.2.1"
serde = "1.0.145"
log = "0.4.20"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
