[package]
name = "mixlayer-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
serde = { workspace = true }
mixlayer-data = { path = "../data" }
log = { workspace = true }
serde_json = "1.0.108"
anyhow.workspace = true
