[package]
name = "valence-names"
version = "0.1.0"
edition = "2021"

[package.metadata.valence]
app-name = "valence-names-example"

[dependencies]
valence = { path = "../../lib" }

[lib]
crate-type = ["cdylib"]